import { Sound, SoundType } from "@/types/sound";
import { SoundIcons } from "@/components/icons/sound-icons";

import { SOUND_FILES_BASE_URL, SOUND_FILES_EXTENSION } from "./common";

export const allSounds: Sound[] = [
  {
    id: SoundType.RainOnTent,
    playing: false,
    volume: 0.5,
    name: "Rain Tent",
    url: `${SOUND_FILES_BASE_URL}/rain-tent/rain-tent${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.rainOnTent,
  },
  {
    id: SoundType.Waves,
    playing: false,
    volume: 0.5,
    name: "Waves",
    url: `${SOUND_FILES_BASE_URL}/waves/waves${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.waves,
  },
  {
    id: SoundType.TropicalForest,
    playing: false,
    volume: 0.5,
    name: "Tropical Forest",
    url: `${SOUND_FILES_BASE_URL}/tropical-forest/tropical-forest${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.tropicalForest,
  },
  {
    id: SoundType.Campfire,
    playing: false,
    volume: 0.5,
    name: "Campfire",
    url: `${SOUND_FILES_BASE_URL}/fireplace/fireplace${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.campfire,
  },
  {
    id: SoundType.ThunderStorm,
    playing: false,
    volume: 0.5,
    name: "Thunder Storm",
    url: `${SOUND_FILES_BASE_URL}/thunderstorm/thunderstorm${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.thunderstorm,
  },
  {
    id: SoundType.Train,
    playing: false,
    volume: 0.5,
    name: "Train",
    url: `${SOUND_FILES_BASE_URL}/train/train${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.train,
  },
  {
    id: SoundType.CoffeeShop,
    playing: false,
    volume: 0.5,
    name: "Coffee Shop",
    url: `${SOUND_FILES_BASE_URL}/coffeeshop/coffeeshop${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.coffee,
  },
  {
    id: SoundType.Underwater,
    playing: false,
    volume: 0.5,
    name: "Underwater",
    url: `${SOUND_FILES_BASE_URL}/underwater/underwater${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.underwater,
  },
  {
    id: SoundType.WhiteNoise,
    playing: false,
    volume: 0.5,
    name: "White Noise",
    url: `${SOUND_FILES_BASE_URL}/white-noise/white-noise${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.whiteNoise,
  },
  {
    id: SoundType.PinkNoise,
    playing: false,
    volume: 0.5,
    name: "Pink Noise",
    url: `${SOUND_FILES_BASE_URL}/pink-noise/pink-noise${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.pinkNoise,
  },
  {
    id: SoundType.BrownNoise,
    playing: false,
    volume: 0.5,
    name: "Brown Noise",
    url: `${SOUND_FILES_BASE_URL}/brown-noise/brown-noise${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.brownNoise,
  },
  {
    id: SoundType.Cicadas,
    playing: false,
    volume: 0.5,
    name: "Cicadas",
    url: `${SOUND_FILES_BASE_URL}/cicada/cicada${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.cicadas,
  },
  {
    id: SoundType.SpaceEngine,
    playing: false,
    volume: 0.5,
    name: "Space Engine",
    url: `${SOUND_FILES_BASE_URL}/space-engine/space-engine${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.spaceEngine,
  },
  {
    id: SoundType.Wind,
    playing: false,
    volume: 0.5,
    name: "Wind",
    url: `${SOUND_FILES_BASE_URL}/wind/wind${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.wind,
  },
  {
    id: SoundType.WindHowling,
    playing: false,
    volume: 0.5,
    name: "Howling Wind",
    url: `${SOUND_FILES_BASE_URL}/wind-howling/wind-howling${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.windHowling,
  },
  {
    id: SoundType.Cityscape,
    playing: false,
    volume: 0.5,
    name: "Cityscape",
    url: `${SOUND_FILES_BASE_URL}/city-scape/city-scape${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.cityScape,
  },
  {
    id: SoundType.Water,
    playing: false,
    volume: 0.5,
    name: "Water",
    url: `${SOUND_FILES_BASE_URL}/river-stream/water${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.water,
  },
  {
    id: SoundType.SummerNight,
    playing: false,
    volume: 0.5,
    name: "Summer Night",
    url: `${SOUND_FILES_BASE_URL}/summer-nights/summer-nights${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.summerNight,
  },
  {
    id: SoundType.Fan,
    playing: false,
    volume: 0.5,
    name: "Fan",
    url: `${SOUND_FILES_BASE_URL}/fan/fan${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.fan,
  },
  {
    id: SoundType.Leaves,
    playing: false,
    volume: 0.5,
    name: "Leaves",
    url: `${SOUND_FILES_BASE_URL}/leaves/leaves${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.autumn,
  },
  {
    id: SoundType.Airplane,
    playing: false,
    volume: 0.5,
    name: "Airplane",
    url: `${SOUND_FILES_BASE_URL}/airplane/airplane${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.airplane,
  },
  {
    id: SoundType.Bubbles,
    playing: false,
    volume: 0.5,
    name: "Bubbles",
    url: `${SOUND_FILES_BASE_URL}/bubbles/bubbles${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.bubbles,
  },
  {
    id: SoundType.Waterfall,
    playing: false,
    volume: 0.5,
    name: "Waterfall",
    url: `${SOUND_FILES_BASE_URL}/waterfall/waterfall${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.waterfall,
  },
  {
    id: SoundType.Whale,
    playing: false,
    volume: 0.5,
    name: "Whale",
    url: `${SOUND_FILES_BASE_URL}/whale/whale${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.whale,
  },
  {
    id: SoundType.Fire,
    playing: false,
    volume: 0.5,
    name: "Bonfire",
    url: `${SOUND_FILES_BASE_URL}/fire/fire${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.fire,
  },
  {
    id: SoundType.WashingMachine,
    playing: false,
    volume: 0.5,
    name: "Washing Machine",
    url: `${SOUND_FILES_BASE_URL}/washing-machine/washing-machine${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.washingMachine,
  },
  {
    id: SoundType.Rain,
    playing: false,
    volume: 0.5,
    name: "Rain",
    url: `${SOUND_FILES_BASE_URL}/rain-low/rain-low${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.rain,
  },
  {
    id: SoundType.RainOnUmbrella,
    playing: false,
    volume: 0.5,
    name: "Rain On Umbrella",
    url: `${SOUND_FILES_BASE_URL}/rain-on-umbrella/rain-on-umbrella${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.rainOnUmbrella,
  },
  {
    id: SoundType.CosmicSounds,
    playing: false,
    volume: 0.5,
    name: "Cosmic Sounds",
    url: `${SOUND_FILES_BASE_URL}/cosmos/cosmos${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.cosmos,
  },
  {
    id: SoundType.Forest,
    playing: false,
    volume: 0.5,
    name: "Forest",
    url: `${SOUND_FILES_BASE_URL}/forest/forest${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.forest,
  },
  {
    id: SoundType.OceanWaves,
    playing: false,
    volume: 0.5,
    name: "Ocean Waves",
    url: `${SOUND_FILES_BASE_URL}/rain-low/rain-low${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.oceanWaves,
  },
  {
    id: SoundType.WaterStream,
    playing: false,
    volume: 0.5,
    name: "Water Stream",
    url: `${SOUND_FILES_BASE_URL}/water-stream/water-stream${SOUND_FILES_EXTENSION}`,
    icon: SoundIcons.waterStream,
  },
];
